# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import logging
import os
import sys
import threading
import webbrowser

DASHBOARD_PORT = 5050
DASHBOARD_URL = f'http://127.0.0.1:{DASHBOARD_PORT}'
def start_dashboard() -> Any:
    ...

def open_dashboard() -> Any:
    ...

def main() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import __future__
import typing
import flask.json.jsonify
import importlib
import importlib.metadata
import warnings
import collections
import collections.abc
import sys
import weakref
import datetime
import inspect
import itertools
import types
import urllib
import urllib.parse
import click
import werkzeug
import werkzeug.datastructures
import werkzeug.datastructures.Headers
import werkzeug.datastructures.ImmutableDict
import werkzeug.exceptions
import werkzeug.routing
import werkzeug.routing.BuildError
import werkzeug.routing.MapAdapter
import werkzeug.routing.RequestRedirect
import werkzeug.routing.RoutingException
import werkzeug.routing.Rule
import werkzeug.serving
import werkzeug.wrappers
import werkzeug.wrappers.Response
import werkzeug.wsgi
import ntpath
import asgiref
import asgiref.sync
import ast
import platform
import re
import traceback
import functools
import operator
import click.core
import werkzeug.run_simple
import werkzeug.utils
import flask.Flask
import dotenv
import ssl
import cryptography
import code
import readline
import rlcompleter
import errno
import json
import contextvars
import jinja2
import jinja2.loaders
import werkzeug.local
import importlib.util
import dataclasses
import decimal
import uuid
import werkzeug.http
import base64
import markupsafe
import markupsafe.Markup
import flask.json.dumps
import flask.json.loads
import logging
import _frozen_importlib_external
import werkzeug.routing.Map
import werkzeug.sansio
import werkzeug.sansio.response
import collections.defaultdict
import pathlib
import jinja2.BaseLoader
import jinja2.FileSystemLoader
import hashlib
import itsdangerous
import itsdangerous.BadSignature
import itsdangerous.URLSafeTimedSerializer
import werkzeug.datastructures.CallbackDict
import blinker
import blinker.Namespace
import jinja2.Environment
import jinja2.Template
import jinja2.TemplateNotFound
import contextlib
import copy
import werkzeug.test
import click.testing
import werkzeug.wrappers.Request
import time
import urllib.request
import netrc
import enum
import h2
import certifi
import json.dumps
import codecs
import io
import zlib
import brotli
import brotlicffi
import zstandard
import pygments
import pygments.lexers
import pygments.util
import rich
import rich.console
import rich.markup
import rich.progress
import rich.syntax
import rich.table
import email
import email.message
import http
import http.cookiejar
import mimetypes
import sniffio
import trio
import asyncio
import httpcore
import socksio
import ipaddress
import idna
import threading
import webbrowser
import frontends
import frontends.web_dashboard
import PIL
import PIL.Image
import gi
import gi.repository
import six
import six.moves
import signal
import subprocess
import AppKit
import Foundation
import objc
import PyObjCTools
import PyObjCTools.MachSignals
import tempfile
import atexit
import shutil
import ctypes
import ctypes.wintypes
import pystray._util.serialized_image
import Xlib
import Xlib.display
import Xlib.threaded
import Xlib.XK